package ldtk;

import ldtk.Json;

class World {
	var untypedProject: ldtk.Project; // WARNING: the var type isn't the "complete" project type as generated by macros!
	var json : ldtk.Json.WorldJson;
	var _untypedLevels : Array<ldtk.Level>;

	/** Index in project `worlds` array **/
	public var arrayIndex(default,null) : Int;
	public var iid(default,null) : String;

	public var layout: WorldLayout;
	public var gridWid : Int;
	public var gridHei : Int;



	public function new(project:Project, arrayIdx:Int, json:ldtk.Json.WorldJson) {
		this.untypedProject = project;
		this.arrayIndex = arrayIdx;
		fromJson(json);
	}

	@:keep public function toString() {
		return 'ldtk.World[$layout,$iid]';
	}

	function fromJson(untypedJson:Dynamic) {
		this.json = untypedJson;
		iid = json.iid;
		layout = WorldLayout.createByName( untypedJson.worldLayout);
		// layout = Type.createEnum( WorldLayout, Std.string(json.worldLayout) );
		gridWid = json.worldGridWidth;
		gridHei = json.worldGridHeight;
	}


	function _instanciateLevel(project:ldtk.Project, arrayIndex:Int, json:ldtk.Json.LevelJson) {
		return null; // overriden by Macros.hx
	}
}
